$outFile = ".\coverage.md"

"# File Format Coverage `r`n`r`nThis file is autogenerated`r`n" | Set-Content -Encoding Ascii -Path $outFile
"Extension|Name|Parent Format|Coverage Level|Spec Link|Notes" | Add-Content -Encoding Ascii -Path $outFile
"---------|----|:-----------:|:------------:|---------|-----" | Add-Content -Encoding Ascii -Path $outFile

Import-CSV .\coverage.csv | % { 
	$link = $_.'Specification Link'
	if ([String]::IsNullOrWhiteSpace($link)) {
		$lnk = " "
	} else {
		$lnk = "[Link](" + $link + ")"
	}	
	$_.Extension + "|" + $_.Name + "|" + $_.'Parent Format' + "|" + $_.'Coverage Level' + "|" + $lnk + "|" + $_.Notes | Add-Content -Encoding Ascii -Path $outFile
}