name: Build & Push

on: [push]

jobs:
  build-linux:
    name: Linux Build
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Build
      run: |
        mkdir -p bin/linux
        make clean
        make    
    - name: Run unit Tests
      run: |
        ./bin/linux/unit_tests
    - name: Archive
      uses: actions/upload-artifact@v1
      with:
        name: Linux-binaries
        path: bin/linux
  build-windows:
    name: Windows Build
    runs-on: windows-latest    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true    
    - name: Build
      shell: pwsh      
      run: |
        .\build.ps1    
    - name: Run Unit Tests
      run: |
        .\Bin\x86\Release\unit_tests.exe
        .\Bin\x64\Release\unit_tests.exe
    - name: Archive x86
      uses: actions/upload-artifact@v1
      with:
        name: Windows-x86-binaries
        path: Bin/x86/Release    
    - name: Archive x64
      uses: actions/upload-artifact@v1
      with:
        name: Windows-x64-binaries
        path: Bin/x64/Release
  pre-release:
    name: "Pre Release"
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows]
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Zip Release Items
        run: |
          for i in artifacts/*/; do zip -r "${i%/}.zip" "$i"; done
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            artifacts/*.zip