on:
  workflow_run:
    workflows: ["Build & Push"]
    branches: [master]
    types:
      - completed

name: Run File Tests

jobs:
  file-tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: File Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: bin
      #- name: File Tests
      #  run: |
      #    python runtests.py